export const GET_ALL_TIME_SLOT = 'GET_ALL_TIME_SLOT';
export const CREATE_TIME_SLOT = 'CREATE_TIME_SLOT';
export const DELETE_TIME_SLOT = 'DELETE_TIME_SLOT';
export const TIME_SLOT_DETAIL = 'TIME_SLOT_DETAIL';